### ISSUE TITLE
When I select iPhone X status bar it doesn’t work

### ISSUE THREAD

**Issue by TheAwesomeGuy11** [ryannair05/Little12#16]
I have chosen the iPhone X status bar but it won’t change to it
![0025ED1F-4D3D-4F79-8717-64B3BFDF4412](https://user-images.githubusercontent.com/70926994/109485409-94e94080-7ad1-11eb-940d-a214f954794d.png)

**Comment by jaytj95** [comment]
+1, but iPad style works for me

**Comment by ryannair05** [comment]
Fixed in version 1.0.1
